
sudo: false

language: scala

scala:
- 2.11.8

jdk:
- oraclejdk8

cache:
  directories:
    - '$HOME/.ivy2/cache'

script:
  - sbt clean coverage test coverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)

sudo: required

services:
  - docker

before_install:
- sudo chmod +x start-setup-couchbase.sh
- sudo ./start-setup-couchbase.sh